name: CI Pipeline

on:                     # Cuándo se ejecuta
  push:
    branches: [ main ]  # Solo cuando hay un push en main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:                   # Qué tareas ejecuta
  build:
    runs-on: ubuntu-latest  # Máquina virtual de GitHub

    steps:               # Pasos a ejecutar
      - name: Checkout code
        uses: actions/checkout@v4   # Descarga el código del repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: run build
        run: npm run build